pluginGroup = com.simi.labs.workflowtrace
pluginName = workflow-trace
pluginRepositoryUrl = https://github.com/saidake/workflow-trace
pluginVersion = 0.0.1
pluginSinceBuild = 251
pluginUntilBuild = 253.*
platformType = IC
platformVersion = 2025.1
platformPlugins =
platformBundledPlugins =
gradleVersion = 8.13
kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
